### ISSUE TITLE
ShowerStartPosition type mismatches after breaking change updates

### ISSUE THREAD

**Issue by absolution1** [LArSoft/larpandora#30]
The ShowerStartPosition key parameter was updated to be a geo::Point_t in a recent update: https://github.com/LArSoft/larpandora/blame/develop/larpandora/LArPandoraEventBuilding/LArPandoraShower/LArPandoraModularShowerCreation_module.cc#L346

The tool that calculate the position had two branches of logic and one of those was also updated: https://github.com/LArSoft/larpandora/blame/17891334919f3f03f9960d60606270816bc2e92b/larpandora/LArPandoraEventBuilding/LArPandoraShower/Tools/ShowerPFPVertexStartPosition_tool.cc#L129

but the other remained a TVector3: https://github.com/LArSoft/larpandora/blame/17891334919f3f03f9960d60606270816bc2e92b/larpandora/LArPandoraEventBuilding/LArPandoraShower/Tools/ShowerPFPVertexStartPosition_tool.cc#L88

When the 2nd route is chosen, any downstream use of the start position throws an exception:

`%MSG-s ArtException:  PostEndJob 13-Jan-2023 08:37:03 CST ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- OtherArt BEGIN
      ---- ShowerElementHolder BEGIN
        Trying to get Element: ShowerStartPosition. This element you are filling is not the correct type
        The above exception was thrown while processing module LArPandoraModularShowerCreation/pandoraShower run: 20000001 subRun: 0 event: 2
      ---- ShowerElementHolder END
    ---- OtherArt END
    Exception going through path reco
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
---- FatalRootError BEGIN
  Fatal Root Error: TTree::SetEntries
  Tree branches have different numbers of entries, eg art::TriggerResults_TriggerResults__Reco. has 1 entries while EventAuxiliary has 10 entries.
  ROOT severity: 2000
---- FatalRootError END`

The fix should be fairly straight forward.  A PR will be issued shortly.

Thanks to @lpaulucc for pointing out the thrown exception.

**Comment by knoepfel** [comment]
Sorry about that, @absolution1 and @lpaulucc.  I thought I got all of the places where that could happen.  Obviously not.

**Comment by henrylay97** [comment]
While testing in SBND we discovered a further issue of a similar nature. This resulted in a runtime segmentation fault at [this](https://github.com/LArSoft/larpandora/blob/develop/larpandora/LArPandoraEventBuilding/LArPandoraShower/Algs/ShowerElementHolder.hh#L397) line. 

Thanks to help from @absolution1 we traced this issue back to [this](https://github.com/PandoraPFA/larpandora/blob/develop/larpandora/LArPandoraEventBuilding/LArPandoraShower/Tools/ShowerTrackTrajPointDirection_tool.cc#L114) line within the ShowerTrackTrajPointDirection tool. I will open a PR with a fix to this line, we have demonstrated this solves the runtime issue within SBND reconstruction. I haven't scoured the other tools for any similar instances yet.

**Comment by knoepfel** [comment]
@henrylay97, we've created a new issue in Redmine (https://cdcvs.fnal.gov/redmine/issues/27737) to cover any of the remaining uses of `TVector3` that should be converted to `geo::Vector_t`.

**Comment by henrylay97** [comment]
Perfect, thanks Kyle! I'll keep an eye 😊
